name: "Unfi Protect Cam proxy"
description: "Proxy for ONVIF IP cameras to be used in Unif Protect NVR"
version: "2.2.0"
slug: "unifi_proxy"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
